server:
 port: 8082
 context-path: /etjava
spring:
 profiles:    active: dev
 datasource:
   username: root
   password: Karen@1234
   url: jdbc:mysql://192.168.199.108:3306/db_springboot?characterEncoding=utf8

name: etjava
